apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cluster-role
rules:
- apiGroups: [""]
  resources: ["endpoints", "services", "pods", "nodes"]
  verbs: ["list", "watch"]