apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - argotest  # specify the correct namespace
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: 'node-exporter'
            action: keep
