apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'app'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: app
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: appcontainer
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: '8080'
          - source_labels: [__address__]
            target_label: __address__
            regex: (.*):\d+
            replacement: ${1}:8080

      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_k8s_app]
            action: keep
            regex: node-exporter
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: '9100'
