apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'app-deployment'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: app
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: '8080'
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: argotest
